# test_DELETE_device.tavern.yaml

---

test_name: DELETE Device 

marks:
  - delete
  

stages:
  - name: Confirm the posted device, based on a Mac Address, on a local server.
    request:
      url: http://localhost:65069/devices/57700b5234373535534252777d205451/subdevices
      method: GET
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
    response:
      status_code: 200
      
  - name: Delete the posted device, based on a Mac Address, on a local server.
    request:
      url: http://localhost:65069/devices/57700b5234373535534252777d205451
      method: DELETE
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
    response:
      status_code: 204

  - name: Confirm the delete posted device, based on a Mac Address, on a local server.
    request:
      url: http://localhost:65069/devices/57700b5234373535534252777d205451
      method: GET
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
    response:
      status_code: 404

  - name: Confirm the delete posted subdevices, based on a Mac Address, on a local server.
    request:
      url: http://localhost:65069/devices/57700b5234373535534252777d205451/subdevices
      method: GET
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
    response:
      status_code: 400



