# test_GET_subDevices.tavern.yaml

---

test_name: GET SubDevices 

marks:
  - get

stages:
  - name: Get a list of subdevices for an existing device on the staging server.
    skip: True
    request:
      url: https://api-stage.apps.bluecats.com/devices/57700b5234373535534252777d205451/subdevices
      method: GET
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
    response:
      status_code: 200