# test_GET_device.tavern.yaml

---

test_name: GET Device

marks:
  - get

stages:
  - name: Get a single device, based on a Mac Address, on the stage server.
    skip: False
    request:
      url: https://api-stage.apps.bluecats.com/devices
      params:
        identifier: E4956E40DFB0
      method: GET
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
    response:
      status_code: 200