# test_GET_devices.tavern.yaml

---

test_name: GET Devices 

stages:
  - name: Get a list of devices on the stage server.
    skip: True
    request:
      url: https://api-stage.apps.bluecats.com/devices
      method: GET
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
    response:
      status_code: 200