# test_CRUD_device.tavern.yaml

---

test_name: GET Device Original

marks:
  - patch

stages:
  - name: Get the original device, based on the device id, on the stage server.
    skip: True
    request:
      url: https://api-stage.apps.bluecats.com/devices/10746901-f7a6-aea0-ac49-67304b51bd17
      method: GET
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
    response:
      status_code: 200
      body: 
        device:
          name: "ConferenceRoom"

test_name: PATCH Device Original

marks:
  - patch

stages:
  - name: Patch a single device, based on the device id, on the stage server.
    request:
      url: https://api-stage.apps.bluecats.com/devices/10746901-f7a6-aea0-ac49-67304b51bd17
      method: PATCH
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
      json:
        name: "Test Dev Edge"
    response:
      status_code: 200
      body: 
        device:
          name: "Test Dev Edge"

test_name: PATCH Device Confirm

marks:
  - patch

stages:
  - name: Confirm the device patch worked, based on the device id, on the stage server.
    request:
      url: https://api-stage.apps.bluecats.com/devices/10746901-f7a6-aea0-ac49-67304b51bd17
      method: GET
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
    response:
      status_code: 200
      body: 
        device:
          name: "Test Dev Edge"

test_name: PATCH Device Restore

marks:
  - patch

stages:
  - name: Restore the device with a patch to it original state, based on the device id, on the stage server.
    request:
      url: https://api-stage.apps.bluecats.com/devices/10746901-f7a6-aea0-ac49-67304b51bd17
      method: PATCH
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
      json:
        name: "ConferenceRoom"
    response:
      status_code: 200
      body: 
        device:
          name: "ConferenceRoom"

test_name: GET Device Confirm

marks:
  - patch

stages:
  - name: Confirm the device's restore patch worked, based on the device id, on the stage server.
    request:
      url: https://api-stage.apps.bluecats.com/devices/10746901-f7a6-aea0-ac49-67304b51bd17
      method: GET
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
    response:
      status_code: 200
      body: 
        device:
          name: "ConferenceRoom"
      
      