# test_POST_device.tavern.yaml

---
test_name: POST Device

marks:
  - post
  - skip

stages:
  - name: Confirm the device doesn't already exist, based on the device MAC Address, on the stage server.
    request:
      url: https://api-stage.apps.bluecats.com/devices/17700b5234373535534252777d205457
      method: GET
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
    response:
      status_code: 404

  - name: Post a single device, based on the device json object, on the stage server.
    request:
      url: https://api-stage.apps.bluecats.com/devices
      method: POST
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
      json:
        macAddress: "17700b5234373535534252777d205457"
        serialNumber: "17700b5234373535534252777d205457"
        deviceModelVariant:
          deviceModelID: f01d1601-9da6-e2b1-b444-3e722fda4212
        rfModuleInfo:
          rfModule:
            id: "e187b5b1-c61d-e911-b2fb-0e1e0e0c0534"
        team:
          id: "bc300500-85a2-31b1-e74f-333236827887"
        site:
          id: "f5dd3101-f4a2-7d90-f34b-f4dcc0c3ca46"
    response:
      status_code: 201
      body: 
        device:
          macAddress: "17700b5234373535534252777d205457"
          serialNumber: "17700b5234373535534252777d205457"
          team:
            id: "bc300500-85a2-31b1-e74f-333236827887"
          site:
            id: "f5dd3101-f4a2-7d90-f34b-f4dcc0c3ca46"
          deviceModelVariant:
            deviceModelID: f01d1601-9da6-e2b1-b444-3e722fda4212
          rfModuleInfo:
            rfModule:
              id: "e187b5b1-c61d-e911-b2fb-0e1e0e0c0534"
            macAddress: "17700b5234373535534252777d205457"
            serialNumber: "17700b5234373535534252777d205457"




      


      
      