# test_PATCH_devices_0001.tavern.yaml

---

test_name: PATCH Devices Test - 0001 - DevicesV3Controller.cs (Local Environment) 

marks:
  - patch
  - skip 

stages:
  - name: Get the original device based on the device id.
    request:
      url: http://localhost:65069/devices/17700b5234373535534252777d205454
      method: GET
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
    response:
      status_code: 200

  - name: Patch a single device based on the device id.
    request:
      url: http://localhost:65069/devices/17700b5234373535534252777d205454
      method: PATCH
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
      json:
        name: "Test Dev Edge"
    response:
      status_code: 200
      body: 
        device:
          name: "Test Dev Edge"

  - name: Confirm the device patch worked based on the device id.
    request:
      url: http://localhost:65069/devices/17700b5234373535534252777d205454
      method: GET
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
    response:
      status_code: 200
      body: 
        device:
          name: "Test Dev Edge"

  - name: Restore the device with a patch to it original state based on the device id.
    request:
      url: http://localhost:65069/devices/17700b5234373535534252777d205454
      method: PATCH
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
      json:
        name: ""
    response:
      status_code: 200
      body: 
        device:
          name: ""




      
      