# test_GET_device.tavern.yaml

---

test_name: GET Device 

stages:
  - name: Get a single device, based on a Mac Address, on a local server.
    request:
      url: http://localhost:65069/devices/E4956E40DFB0
      method: GET
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
    response:
      status_code: 200