# test_PUT_beaconFirmware.tavern.1.yaml

---

test_name: PUT Beacon Version Confirmation - BeaconFirmwareV3Controller

marks:
  - put

stages:
  - name: Return firmware OTA file by beacon identifier and firmware version on a local server.
    skip: True
    request:
      url: http://localhost:65069/beacons/{identifier}/firmware/{version}/Hex
      method: PUT
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
    response:
      status_code: 200