# test_POST_devices_0001.tavern.yaml

---
test_name: POST Devices Test - 0001 - DevicesV3Controller.cs (Local Environment) 

marks:
  - post
  - skip 

stages:
  - name: Confirm the device doesn't already exist based on a MAC Address.
    request:
      url: http://localhost:65069/devices/17700b5234373535534252777d205456
      method: GET
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
    response:
      status_code: 404

  - name: Post a single device based on a json object.
    request:
      url: http://localhost:65069/devices
      method: POST
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
      json:
        macAddress: "17700b5234373535534252777d205456"
        serialNumber: "17700b5234373535534252777d205456"
        deviceModelVariant:
          deviceModelID: "f01d1601-9da6-e2b1-b444-3e722fda4212"
        rfModuleInfo:
          rfModule:
            id: "e187b5b1-c61d-e911-b2fb-0e1e0e0c0534"
        team:
          id: "bc300500-85a2-31b1-e74f-333236827887"
        site:
          id: "f5dd3101-f4a2-7d90-f34b-f4dcc0c3ca46"
    response:
      status_code: 201




      


      
      