# test_GET_device.tavern.yaml

---

test_name: GET Devices 

marks:
  - get
  
stages:
  - name: Get a single device, based on a Mac Address, on the production server.
    skip: True
    request:
      url: https://api.bluecats.com/devices/E4956E40D05E
      method: GET
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
    response:
      status_code: 200