# test_GET_devices.tavern.yaml

---

test_name: GET Devices 

marks:
  - get

stages:
  - name: Get a list of devices on the production server.
    skip: False
    request:
      url: https://api.bluecats.com/devices
      method: GET
      headers:
        content-type: application/json
        Authorization: "BlueCats {tavern.env_vars.SECRET_AUTH}"
        x-api-version: "3"
    response:
      status_code: 200